### ISSUE TITLE
我下载了但是qt编译是通过不了的

### ISSUE THREAD

**Issue by lcj-cp** [popkc/bookreader#1]
我系统没有安装MS Speech SDK ，然后我自己安装了之后在.pro文件夹里面添加
INCLUDEPATH+=   "C:\Microsoft SDKs\Speech\v11.0\include"
LIBS += -L  "C:\Microsoft SDKs\Speech\v11.0\Lib"
却提示sphelper里里面的头文件找不到#include <atlbase.h>
我使用的是电脑是win10 qt版本5.6.1 mingw32 MSSpeechSDK版本是11
如果您有看见这个问题，麻烦讲下您的见解，感激不尽！

**Comment by popkc** [comment]
你用win10的话可以使用高版本的Qt，然后加上DEFINES += BOOKREADER_USE_QTSPEECH这句，那么就会使用QT自带的语音库wrapper了。
如果你一定要用QT 5.6编译，那么用MSVC来编译。你为什么要用mingw编译呢？我没有试过mingw编译，我不清楚它支不支持ATL，你可以用MSVC来编译啊。
还有MS Speech SDK没必要手动装，你装新版的MSVC的话这东西应该是自带的，反正我是没手动装过。
